name: Spell Check

on:
  push:
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run spell check
        uses: rojopolis/spellcheck-github-actions@v0.33.1
        with:
          config_path: .github/spellcheck.yml
