name: Auto TOC

on:
  push:
    paths:
      - "**/*.md"

jobs:
  generateTOC:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: "**/*.md"
